### ISSUE TITLE
Tries to use a non-existent webcam

### ISSUE THREAD

**Issue by yurivict** [c-koi/zart#11]
```/dev/video0``` is a working webcam on my system.
```zart``` detected it, then tried to open the ```/dev/video1```, it doesn't have a device on it.
Now it  just keeps trying to use video1 and failing. This makes ```zart``` unusable.

**Comment by c-koi** [comment]
The question is (IMHO) : why is there a /dev/video1 file if no device?
There is a dirty fix [here](https://github.com/c-koi/zart/blob/master/src/WebcamSource.cpp#L277) for Fedora (same issue : a single webcam but two /dev/videoN files).
May I assume /etc/os-release is present in FreeBSD?

**Comment by yurivict** [comment]
> The question is (IMHO) : why is there a /dev/video1 file if no device?

You are right, this is how driver devs prefer to do it for whatever reason.

But once you see a device on which all commands fail you should quickly abandon it.

**Comment by c-koi** [comment]
No command actually fails until one (like cv::VideoCapture::set()) simply blocks! So this is really tough to detect. However, it looks like the second device is opened with OpenCV's UNICAP backend, which may be considered obsolete according to opencv/opencv@5869415a57524cf2dfb5eaba5aafa86ceb395d15.
New fix candidate c9b70f1be3714f572c0ceeede2c0b61dd067a8b1 just skips this backend.

**Comment by c-koi** [comment]
Several commits try to make all this more reliable 351d5fd32df3afb3391d4acbf8698397c70d4e2c d1d5192e3856fe38ba7651ef9c4f433d9be0ab5f 5af22bb17990aa4fc10d707228d9cb2a0500e406
Please confirm.

**Comment by yurivict** [comment]
The latest commit doesn't crash, but the video pane is black.

```
Info: creating stash file /usr/ports/multimedia/zart/work/zart-c8a87cf/.qmake.stash
Project MESSAGE: GMIC_PATH is set (/usr/ports/multimedia/zart/work/gmic-2.7.4/src)
Project MESSAGE: G'MIC repository was found (/usr/ports/multimedia/zart/work/gmic-2.7.4/src)
Project MESSAGE: Release build
Project MESSAGE: Detected OS is PreeBSD
```
