### ISSUE TITLE
compilation fails : class cv::VideoCapture has no member named getBackendName

### ISSUE THREAD

**Issue by HJarausch** [c-koi/zart#12]
I have opencv-3.4.1 installed here (GenToo)

Compilation of zart (GIT) fails with

src/WebcamSource.cpp: In static member function 'static const QList<int>& WebcamSource::getWebcamList()':
src/WebcamSource.cpp:112:44: error: 'class cv::VideoCapture' has no member named 'getBackendName'
  112 |       if (std::string("UNICAP") != capture.getBackendName().c_str()) {
      |                                            ^~~~~~~~~~~~~~
src/WebcamSource.cpp: In static member function 'static void WebcamSource::retrieveWebcamResolutions(const QList<int>&, QSplashScreen*, QStatusBar*)':
src/WebcamSource.cpp:286:79: error: 'class cv::VideoCapture' has no member named 'getBackendName'
  286 | le && capture.open(*it) && (std::string("UNICAP") != capture.getBackendName().c_str())) {
      |                                                              ^~~~~~~~~~~~~~

**Comment by c-koi** [comment]
Fixed by 6d129ea44928338ea6f249a9139b946cd4da8465
