### ISSUE TITLE
Provide desktop file

### ISSUE THREAD

**Issue by City-busz** [c-koi/zart#16]
Please include a .desktop file that meets the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/), so the application could be appear in the application launchers on Linux.

**Comment by c-koi** [comment]
See 4b4b6456bc55da906748a13bcf5f92f08c8a05b7

**Comment by dtschump** [comment]
Just made https://github.com/dtschump/gmic/commit/f6f3af03e4d9dae25136c56f01aa67b88c4ae5b0 
Building .deb packages now to check.
