### ISSUE TITLE
errors with cimg-2.3.1 and gmic-2.3.1

### ISSUE THREAD

**Issue by stefantalpalaru** [c-koi/zart#3]
When trying to apply the "bokeh" filter on a webcam input:
```
*** Error in ./foo/fx_bokeh_preview/gui_split_preview/ *** Command 'gui_split_preview': Invalid argument '_output_mode=0 fx_bokeh 3,8,0,30,8,4,0(...),1,2,170,130,20,110,0.15,0,110,0.15,0'.
```

**Comment by dtschump** [comment]
Did you try to apply the Bokeh filter from the plug-in, or from the command line ?
Using the plug-in gives no error for me.
If you used the command line, please copy/paste the command used so we can try to understand what is going on.

**Comment by stefantalpalaru** [comment]
> Did you try to apply the Bokeh filter from the plug-in, or from the command line ?

From the Zart GUI.

**Comment by dtschump** [comment]
Ah yes, I think I've forgot to update the ZArt commands. I'll take a look ASAP.
Thanks for reporting.

**Comment by dtschump** [comment]
Commit https://github.com/c-koi/zart/commit/00edf034c6ccbe8d48fe540c03b0282b39a80a6c proposes a new working filter file `presets.xml`.

**Comment by stefantalpalaru** [comment]
Works for most filters. One warning I encountered:

[gmic]-1./foo/fx_colorblind_preview/gui_split_preview/ Discard definition of custom command '_split_preview' (1 found, 1972 commands left).
