### ISSUE TITLE
Webcams doesn't work because of use of deprecated API

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [c-koi/zart#8]
I'm using zart with the recent version of Manjaro, OpenCV 4.1.0 and GMIC 2.5.7.
If I select a webcam the possible resolutions are not recognised and if I click on the play button, nothing happens in the GUI. If I start zart through a terminal, each time I try to access a webcam the error message
[ WARN:0] cvCreateCameraCapture doesn't support legacy API anymore.
is shown.

**Comment by hacklab01** [comment]
Same for video files. In faact nothing other then images work for OpenCV .

**Comment by c-koi** [comment]
See c29111d56c8fb52d0beb2999d9fb9a164850b382
Tested only with OpenCV 3.4.4 though.

**Comment by kuboosoft** [comment]
Hi; then, exist news about compatibility with OpenCV 4.1.0?

**Comment by java-py-c-cpp-js** [comment]
Currently, I'm using OpenCV 4.1.0 with zart 2.6.7 and the error message is still the same:
[ WARN:0] global /build/opencv/src/opencv-4.1.1/modules/videoio/src/videoio_c.cpp (15) cvCreateCameraCapture cvCreateCameraCapture doesn't support legacy API anymore.

**Comment by kuboosoft** [comment]
@java-py-c-cpp-js Then maybe is necessary build and use with a 3.x opencv; transitional; waiting the modernization of zart...

**Comment by data-man** [comment]
ArchLinux, ZArt 3.2.2 (package's version 2.7.0-1), GMIC 2.7.0-1, OpenCV 4.1.1-1
Works fine.

**Comment by java-py-c-cpp-js** [comment]
After the update came available for Manjaro, it is working there, too.
